### ISSUE TITLE
Possible t0 offset with different Productions?

### ISSUE THREAD

**Issue by anupama-reghunath** [ShipSoft/FairShip#520]
Hi All,
Below I attach a plot comparing the average times recorded by the cells in the SBT(Old geometry and hence 2000 cell indices). It seems that the times recorded by the MuonBackground hits( mainly from EM debris) colored in green have an offset in time compared to the DIS generations. Not sure what this is causing? Any ideas how to resolve this?
![Screenshot from 2024-09-25 12-46-24](https://github.com/user-attachments/assets/4f342792-e9ab-49b0-92f6-fa23a3f8e52d)

**Comment by olantwin** [comment]
The overall timescale cannot be correct: the highest values are years!
Could there be an incorrect scale-factor somewhere?

**Comment by anupama-reghunath** [comment]
Yes I agree, but if you visualise all the time values stored which could be skewing the average, these numbers occur quite often.
![image](https://github.com/user-attachments/assets/bea838e6-6c89-499f-95be-be8ce1eb717a)

**Comment by olantwin** [comment]
There seem to be at least two issues:
1. Offsets in time between the different types of events (some are probably physical and might be useful to distinguish processes!)
2. The time *cannot* be in nanoseconds, there must be a mistake in the calculation of the unit.

**Comment by anupama-reghunath** [comment]
I've updated the  plot to be correctly color coded now. 
The times here are the absolute values stored in the registered hits. The start time of for example for MCTrack[0] for neuDIS usually is in the range of 10^6 ns.
The hits with large time usually have an energy deposition of ~1MeV, and they have no track saved unfortunately to explore further. Could these be from neutrons?

**Comment by olantwin** [comment]
Part of this should be now fixed with #570

**Comment by anupama-reghunath** [comment]
Yes, and with the new muonDIS production from #510 this seems to look okay for now,
![image](https://github.com/user-attachments/assets/73d87e62-5364-47fc-a4e3-635565a80eeb)
 might need to run a larger statistics later for a complete check .

**Comment by olantwin** [comment]
So #510 should fix the remainder of the issue?
For signal and EMBG, it seems like there are still two populations.

Could you plot a 1-D histogram of the time distribution? The effect seems constant for all cells.

**Comment by anupama-reghunath** [comment]
The previous plot maybe misleading, with more statistics, attached is all the times registered for neuDIS samples ( not the average over all the events). and while the offset is gone, time registered still doesnt make sense.

![image](https://github.com/user-attachments/assets/76a89978-cd53-4e5e-9880-5a6d37de6e0f)
