### ISSUE TITLE
ShipDigiReco is not working properly

### ISSUE THREAD

**Issue by Gfrisella** [ShipSoft/FairShip#793]
I'm recently using ShipReco to analyze the combinatorial background.
I had some issue: 

1. The fit of the track depends from the initial guess point (set to be the center of the Decay Vessel (why??))
2. When the GenFit doesn't succeed to estimate a track, it compromise all the others:
```
DAF::processTrack, trackRep  0x5645a9ce0b30, iteration 4, beta = 0.562341
genfit::Exception thrown with excString:
RKTrackRep::RKutta ==> momentum too low: 3.46283 MeV
in line: 1847 in file: /cvmfs/ship.cern.ch/25.01/sw/SOURCES/GenFit/main/ce9ae2a803/trackReps/src/RKTrackRep.cc
with fatal flag 0
DAF::Kalman could not fit!
```
Few raw laters...:
```
Traceback (most recent call last):
  File "/afs/cern.ch/user/g/gfrisell/link_afs/temp/sw/slc9_x86-64/FairShip/master-local1/macro/ShipRecoGu.py", line 179, in <module>
    SHiP.reconstruct()
  File "/afs/cern.ch/user/g/gfrisell/link_afs/temp/sw/slc9_x86-64/FairShip/master-local1/python/shipDigiReco.py", line 204, in reconstruct
    ntracks = self.findTracks()
  File "/afs/cern.ch/user/g/gfrisell/link_afs/temp/sw/slc9_x86-64/FairShip/master-local1/python/shipDigiReco.py", line 1070, in findTracks
    print('save track',theTrack,chi2,nmeas,fitStatus.isFitConverged())
UnboundLocalError: local variable 'chi2' referenced before assignment
```
Removing `--Debug` option:
```
genfit::Exception thrown with excString:
RKTrackRep::RKutta ==> momentum too low: 3.46283 MeV
in line: 1847 in file: /cvmfs/ship.cern.ch/25.01/sw/SOURCES/GenFit/main/ce9ae2a803/trackReps/src/RKTrackRep.cc
with fatal flag 0
finished writing tree
Problem with fittedstate : 2

```
3. If the momentum is too low, shall the track to be consider in any case or discarded beforehand? In reality the detector will have a track point there or there is a threshold in the ADC?
4. It fails sometime with this error:
```
DAF::processTrack, trackRep  0x560809429060, iteration 8, beta = 0.1
genfit::Exception thrown with excString:
MaterialEffects::getMomGammaBeta - Energy <= mass
in line: 378 in file: /cvmfs/ship.cern.ch/25.01/sw/SOURCES/GenFit/main/ce9ae2a803/trackReps/src/MaterialEffects.cc
with fatal flag 0
DAF::Kalman could not fit!
```
Shall it be consider also a problem arise form the too low momenta or something else?

5. When ShipReco is used from /afs to /eos the cp takes more time than expected leading to a crash:
```
The directory analyzed is: /eos/user/g/gfrisell/MS/Piet_1_BKG/0_400000_10400001
Error in <TNetXNGFile::ReadBuffer>: error reading all requested bytes, got 0 of 94
Error in <TKey::ReadFile>: Failed to read data.
Error in <TNetXNGFile::Init>: file root://eoshome-g.cern.ch//eos/user/g/gfrisell/MS/Piet_1_BKG/0_400000_10400001/ship.conical.MuonBack-TGeant4_D_SaveCrit_rec.root is truncated at 1245184 bytes: should be 5298077, trying to recover
TNetXNGFile::Init:0: RuntimeWarning: no keys recovered, file has been made a Zombie
Error in <TNetXNGFile::TNetXNGFile>: Object is in 'zombie' state
```

**Comment by olantwin** [comment]
The $\chi^2$ issue should be fixed in #794.

Could you provide additional information for 5.?

It would be good to make separate issues for unrelated issues, so that they can be tracked and addressed separately.

**Comment by olantwin** [comment]
> > The χ 2 issue should be fixed in [#794](https://github.com/ShipSoft/FairShip/pull/794).
> > Could you provide additional information for 5.?
> > It would be good to make separate issues for unrelated issues, so that they can be tracked and addressed separately.
> 
> I'm using a cycle for in ShipReco to analyze all the data I have without loading every time the same geometry:
> 
> ```
> for subdir, _, files in os.walk(maindir):
>     if options.inputFile in files and options.geoFile in files:
>         print("The directory analyzed is:",subdir)
>         origin = os.path.join(subdir, options.inputFile)
>         new = origin.replace('.root','_rec.root')
>         
>         if os.path.exists(new):
>             os.remove(new)
>             print(f"Removed existing file: {new}")
>         os.system('cp '+ origin +' ' + new)
>         #time.sleep(2)  # sleeps needed to avoid crash
>         SHiP = shipDigiReco.ShipDigiReco(new,fgeo)
>         options.nEvents   = min(SHiP.sTree.GetEntries(),options.nEvents)
>         # main loop
>         for global_variables.iEvent in range(options.firstEvent, options.nEvents):
>             if global_variables.iEvent % 1000 == 0 or global_variables.debug:
>                 print('event ', global_variables.iEvent)
>             rc = SHiP.sTree.GetEvent(global_variables.iEvent)
>             SHiP.digitize()
>             SHiP.reconstruct()
>         # memory monitoring
>         # mem_monitor()
>         # end loop over events
>         SHiP.finish()
> ```
> 
> ```
> The directory analyzed is: /eos/user/g/gfrisell/MS/Piet_1_BKG/0_400000_10400001
> Error in <TNetXNGFile::ReadBuffer>: error reading all requested bytes, got 0 of 94
> Error in <TKey::ReadFile>: Failed to read data.
> Error in <TNetXNGFile::Init>: file root://eoshome-g.cern.ch//eos/user/g/gfrisell/MS/Piet_1_BKG/0_400000_10400001/ship.conical.MuonBack-TGeant4_D_SaveCrit_rec.root is truncated at 1245184 bytes: should be 5298077, trying to recover
> TNetXNGFile::Init:0: RuntimeWarning: no keys recovered, file has been made a Zombie
> Error in <TNetXNGFile::TNetXNGFile>: Object is in 'zombie' state
> ```

We definitely need to clean up the way files are opened in ShipReco, it's a complete mess. How much data are we talking about?

**Comment by olantwin** [comment]
> 1. The fit of the track depends from the initial guess point (set to be the center of the Decay Vessel (why??))

See https://github.com/ShipSoft/FairShip/pull/772 and https://github.com/ShipSoft/FairShip/issues/763

**Comment by Gfrisella** [comment]
> > 1. The fit of the track depends from the initial guess point (set to be the center of the Decay Vessel (why??))
> 
> See [#772](https://github.com/ShipSoft/FairShip/pull/772) and [#763](https://github.com/ShipSoft/FairShip/issues/763)

This doesn't explain why it is needed.
I got that the point is relevant since it knows the matter (from geofile) passed by muons between the guess point and the tracking stations. Still not get why in the middle of decay vessel, old legacy? Should better after the decay vessel, to reduce the impact of the matter?

**Comment by Gfrisella** [comment]
`
    When ShipReco is used from /afs to /eos the cp takes more time than expected leading to a crash:

The directory analyzed is: /eos/user/g/gfrisell/MS/Piet_1_BKG/0_400000_10400001
Error in <TNetXNGFile::ReadBuffer>: error reading all requested bytes, got 0 of 94
Error in <TKey::ReadFile>: Failed to read data.
Error in <TNetXNGFile::Init>: file root://eoshome-g.cern.ch//eos/user/g/gfrisell/MS/Piet_1_BKG/0_400000_10400001/ship.conical.MuonBack-TGeant4_D_SaveCrit_rec.root is truncated at 1245184 bytes: should be 5298077, trying to recover
TNetXNGFile::Init:0: RuntimeWarning: no keys recovered, file has been made a Zombie
Error in <TNetXNGFile::TNetXNGFile>: Object is in 'zombie' state
`

This has been solved using a delay of 2 seconds, the causes of such delay between afs and eos are not fully understood by me.
